### ISSUE TITLE
WebRTC Sync

### ISSUE THREAD

**Issue by maxstoller** [MaMazav/MaMazav.github.io#1]
Hi,

Sorry, I couldn't figure out another way to contact you. I hope you don't mind me posting here. I was wondering if you ever figured out a solution to [this](http://stackoverflow.com/questions/30391939/synchronization-of-data-with-video-using-webrtc) Stackoverflow post? I've been exploring using an invisible watermark to embed data in the stream, but I figured I'd reach out just in case you found a better solution.

Thanks so much.

**Comment by MaMazav** [comment]
Unfortunately I found no magic solution. I don't have any new ideas except of those detailed in the stackoverflow question. My opinion is that you should choose the method fits best for your needs (the pros and cons of each method are detailed in the question).
Sorry.

**Comment by maxstoller** [comment]
Got it. Thanks anyway!
